create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('ADMIN', 'WAITER');
  end if;

  if not exists (select 1 from pg_type where typname = 'event_action') then
    create type public.event_action as enum ('CALL_WAITER', 'REQUEST_BILL', 'VIEW_MENU');
  end if;

  if not exists (select 1 from pg_type where typname = 'event_status') then
    create type public.event_status as enum ('PENDING', 'ACKNOWLEDGED', 'RESOLVED');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_enum
    where enumtypid = 'public.event_action'::regtype
      and enumlabel = 'VIEW_MENU'
  ) then
    alter type public.event_action add value 'VIEW_MENU';
  end if;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role public.app_role not null default 'WAITER',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.restaurant_tables (
  id uuid primary key default gen_random_uuid(),
  table_name text not null unique,
  active boolean not null default true,
  sector text,
  ordering_url text not null,
  menu_url_override text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.settings (
  id bigint primary key generated by default as identity,
  restaurant_name text not null,
  global_menu_url text,
  direct_order_url text,
  logo_url text,
  mobile_banner_url text,
  mobile_banner_text text,
  custom_message text,
  brand_primary_color text not null default '#0f172a',
  brand_secondary_color text not null default '#b45309',
  brand_tertiary_color text not null default '#f8f5ef',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  table_id uuid not null references public.restaurant_tables(id) on delete cascade,
  action public.event_action not null,
  status public.event_status not null default 'PENDING',
  customer_email text,
  marketing_opt_in boolean not null default false,
  session_id uuid not null,
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_events_status_created_at on public.events(status, created_at);
create index if not exists idx_events_table_session_action_created_at
  on public.events(table_id, session_id, action, created_at desc);
create index if not exists idx_events_created_at on public.events(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_restaurant_tables_updated_at on public.restaurant_tables;
create trigger set_restaurant_tables_updated_at
before update on public.restaurant_tables
for each row execute function public.set_updated_at();

drop trigger if exists set_settings_updated_at on public.settings;
create trigger set_settings_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role public.app_role;
begin
  requested_role := case
    when coalesce(new.raw_user_meta_data ->> 'role', '') = 'ADMIN' then 'ADMIN'::public.app_role
    else 'WAITER'::public.app_role
  end;

  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    requested_role
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_role()
returns public.app_role
language sql
stable
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.create_table_event(
  p_table_id uuid,
  p_session_id uuid,
  p_action public.event_action,
  p_customer_email text,
  p_marketing_opt_in boolean default false
)
returns table(
  ok boolean,
  message text,
  error_code text,
  retry_after_seconds integer,
  table_name text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  active_table public.restaurant_tables%rowtype;
  recent_event public.events%rowtype;
begin
  select *
  into active_table
  from public.restaurant_tables
  where id = p_table_id
    and active = true;

  if not found then
    return query
    select false, 'Mesa no disponible', 'TABLE_NOT_FOUND', null::integer, null::text;
    return;
  end if;

  select *
  into recent_event
  from public.events
  where table_id = p_table_id
    and session_id = p_session_id
    and action = p_action
    and created_at >= timezone('utc', now()) - interval '60 seconds'
  order by created_at desc
  limit 1;

  if found then
    return query
    select
      false,
      format(
        'Ya recibimos tu pedido de %s. Esperá un momento para volver a enviarlo.',
        case p_action
          when 'CALL_WAITER'::public.event_action then 'Llamar al mozo'
          when 'REQUEST_BILL'::public.event_action then 'Pedir la cuenta'
          when 'VIEW_MENU'::public.event_action then 'Cliente viendo menú'
        end
      ),
      'COOLDOWN',
      greatest(
        1,
        ceil(
          extract(
            epoch
            from (recent_event.created_at + interval '60 seconds' - timezone('utc', now()))
          )
        )::integer
      ),
      active_table.table_name;
    return;
  end if;

  insert into public.events (
    table_id,
    action,
    status,
    customer_email,
    marketing_opt_in,
    session_id
  )
  values (
    p_table_id,
    p_action,
    'PENDING',
    p_customer_email,
    coalesce(p_marketing_opt_in, false),
    p_session_id
  );

  return query
  select
    true,
    format(
      '%s enviado para %s.',
      case p_action
        when 'CALL_WAITER'::public.event_action then 'Llamar al mozo'
        when 'REQUEST_BILL'::public.event_action then 'Pedir la cuenta'
        when 'VIEW_MENU'::public.event_action then 'Cliente viendo menú'
      end,
      active_table.table_name
    ),
    null::text,
    null::integer,
    active_table.table_name;
end;
$$;

grant execute on function public.create_table_event(uuid, uuid, public.event_action, text, boolean)
to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.settings enable row level security;
alter table public.events enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.current_role() = 'ADMIN');

drop policy if exists "profiles_admin_manage" on public.profiles;
create policy "profiles_admin_manage"
on public.profiles
for all
to authenticated
using (public.current_role() = 'ADMIN')
with check (public.current_role() = 'ADMIN');

drop policy if exists "tables_public_read_active" on public.restaurant_tables;
create policy "tables_public_read_active"
on public.restaurant_tables
for select
to anon, authenticated
using (active = true or public.current_role() in ('ADMIN', 'WAITER'));

drop policy if exists "tables_admin_manage" on public.restaurant_tables;
create policy "tables_admin_manage"
on public.restaurant_tables
for all
to authenticated
using (public.current_role() = 'ADMIN')
with check (public.current_role() = 'ADMIN');

drop policy if exists "settings_public_read" on public.settings;
create policy "settings_public_read"
on public.settings
for select
to anon, authenticated
using (true);

drop policy if exists "settings_admin_manage" on public.settings;
create policy "settings_admin_manage"
on public.settings
for all
to authenticated
using (public.current_role() = 'ADMIN')
with check (public.current_role() = 'ADMIN');

drop policy if exists "events_public_insert" on public.events;
create policy "events_public_insert"
on public.events
for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.restaurant_tables t
    where t.id = table_id
      and t.active = true
  )
);

drop policy if exists "events_staff_read" on public.events;
create policy "events_staff_read"
on public.events
for select
to authenticated
using (public.current_role() in ('ADMIN', 'WAITER'));

drop policy if exists "events_staff_update" on public.events;
create policy "events_staff_update"
on public.events
for update
to authenticated
using (public.current_role() in ('ADMIN', 'WAITER'))
with check (public.current_role() in ('ADMIN', 'WAITER'));
